# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080 # WordPress NodePort
        hostPort: 30080
        protocol: TCP
      - containerPort: 30006 # MySQL (optional, if you want external access)
        hostPort: 30006
        protocol: TCP
